language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  # Trunk
  # @link https://github.com/WordPress/WordPress
  - WP_VERSION=master WP_MULTISITE=0
  #- WP_VERSION=master WP_MULTISITE=1
  # WordPress 4.2
  # @link https://github.com/WordPress/WordPress/tree/4.2-branch
  #- WP_VERSION=4.2 WP_MULTISITE=0
  #- WP_VERSION=4.2 WP_MULTISITE=1
  # WordPress 4.1
  # @link https://github.com/WordPress/WordPress/tree/4.1-branch
  #- WP_VERSION=4.1 WP_MULTISITE=0
  #- WP_VERSION=4.1 WP_MULTISITE=1

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mkdir coverage
  # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - export DB_HOST
  - export BASEDIR=`pwd`
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - svn co http://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ ${WP_DEVELOP_DIR}include
  # Set up WordPress configuration.
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - wget -nv -O wp-tests-config.php http://develop.svn.wordpress.org/trunk/wp-tests-config-sample.php
  - sed -i "s:dirname( __FILE__ ) . '/src/':'$WP_DEVELOP_DIR':" wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/$DB_NAME/" wp-tests-config.php
  - sed -i "s/yourusernamehere/$DB_USER/" wp-tests-config.php
  - sed -i "s/yourpasswordhere/$DB_PASS/" wp-tests-config.php
  # Create WordPress database.
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  # Install CodeSniffer for WordPress Coding Standards checks.
  #- git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
  # Install WordPress Coding Standards.
  #- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wordpress-coding-standards
  # Hop into CodeSniffer directory.
  #- cd php-codesniffer
  # Set install path for WordPress Coding Standards.
  # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
  #- scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
  # Hop into themes directory.
  - cd $BASEDIR
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash

script:
  - vendor/bin/phpunit --coverage-clover coverage/clover.xml
  #- $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php

after_script:
  - php vendor/bin/coveralls -v